export interface UserData {
    userId:string,
    phoneNumber:string,
    customerName:string,
    timestamp: string,
    type:string,
    customerCommunicationData:CommunicationHistory[];
}

export interface CommunicationHistory {
    userId: string;
    fromNumber: string;
    fromName: string;
    timestamp: string;
    type: string;
    // Add other properties as needed
  }
const data = [
    {
      "userId": "6",
      "phoneNumber": "+1234567890",
      "customerName": "Nikhil Bhardwaj",
      "timestamp": "2023-09-08T04:54:47.196Z",
      "type": "CHAT",
      "customerCommunicationHistory": [
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Nikhil Bhardwaj",
          "timestamp": "2023-09-08T04:54:47.196Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "01b60e95-c83e-4f7d-816b-387ee062a05b",
          "direction": "OUTBOUND",
          "text": "Sure, Asur. Please email me the pricing details and options at nikhil@example.com. Also, do you offer any financing options?",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        },
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Nikhil Bhardwaj",
          "timestamp": "2023-09-07T16:46:30.058Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "3b9e02f9-874e-464e-ad33-ecc0cfe91c94",
          "direction": "OUTBOUND",
          "text": "Hello, I'm interested in purchasing a car. Can you provide me with some information on the available models?",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        },
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Nikhil Bhardwaj",
          "timestamp": "2023-09-08T07:19:23.770Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "44d9fb58-e249-4d1e-9e0e-3b116f31c9ca",
          "direction": "OUTBOUND",
          "text": "Hi Asur, I have reviewed the pricing details and options. I'm interested in scheduling a test drive. Can you provide me with the available dates and times?",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        },
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Asur Joshi",
          "timestamp": "2086-10-02T15:38:14.784Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "53c04fbe-cc05-4ab9-be4e-44df91fbf2d0",
          "direction": "INBOUND",
          "text": "Hello Nikhil, this is Asur Joshi. Take your time to review the pricing details. If you have any questions or need further assistance, feel free to reach out. I'm here to help!",
          "toName": "Nikhil Bhardwaj",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        },
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Nikhil Bhardwaj",
          "timestamp": "2032-12-30T22:36:58.019Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "5d77c7ff-99f5-4db5-949c-5227e94e17a8",
          "direction": "OUTBOUND",
          "text": "Thank you, Asur. I have received the email. I'll review the pricing details and get back to you soon.",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        },
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Asur Joshi",
          "timestamp": "2089-10-06T07:03:30.789Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "947fdfde-f9b4-4ad3-83ca-93480cb313ad",
          "direction": "INBOUND",
          "text": "Hello Nikhil, I'm glad to hear that you're interested in a test drive. Let me check the availability and get back to you with the available dates and times shortly.",
          "toName": "Nikhil Bhardwaj",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        },
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Nikhil Bhardwaj",
          "timestamp": "2046-10-22T14:53:50.194Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "dec5dc66-f9ab-49ad-9c72-91463bca1842",
          "direction": "OUTBOUND",
          "text": "Hi Asur, I'm interested in purchasing the XYZ car model. Can you provide me with more information on the pricing and available options?",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        },
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Asur Joshi",
          "timestamp": "2098-01-11T13:46:07.319Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "e3a8320e-fce1-41f3-b360-618d811c08b6",
          "direction": "INBOUND",
          "text": "Hi Nikhil, this is Asur Joshi from XYZ Motors. We have a range of car models available. Can you please let me know your preferences or any specific features you're looking for?",
          "toName": "Nikhil Bhardwaj",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        },
        {
          "userId": "6",
          "fromNumber": "+1234567890",
          "fromName": "Asur Joshi",
          "timestamp": "2087-05-01T13:20:06.663Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "ff2f96e9-6c7c-4a54-8335-805b828f6673",
          "direction": "INBOUND",
          "text": "Hello Nikhil, this is Asur Joshi from XYZ Motors. I have the pricing details and available options for the XYZ car model ready. Shall I email them to you?",
          "toName": "Nikhil Bhardwaj",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Nikhil Bhardwaj",
          "customerPhone": "+1756582284"
        }
      ]
    },
    {
      "userId": "1",
      "phoneNumber": "+1234567890",
      "customerName": "Jane Doe",
      "timestamp": "2023-09-08T22:10:12.494Z",
      "type": "CHAT",
      "customerCommunicationHistory": [
        {
          "userId": "1",
          "fromNumber": "+1234567890",
          "fromName": "Jane Doe",
          "timestamp": "2023-09-08T22:10:12.494Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "06ca443c-7686-4bff-8030-38fa8dbfad92",
          "direction": "OUTBOUND",
          "text": "Hello, I'm having trouble with my account. Can you please assist?",
          "toName": "Gus Dakas",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Jane Doe",
          "customerPhone": "+1234567890"
        },
        {
          "userId": "1",
          "fromNumber": "+1234567890",
          "fromName": "Jane Doe",
          "timestamp": "2023-09-07T11:46:18.678Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "0c87435a-2562-4072-b0bd-a65fcc3ff798",
          "direction": "OUTBOUND",
          "text": "My account email is john@example.com",
          "toName": "Gus Dakas",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Jane Doe",
          "customerPhone": "+1234567890"
        },
        {
          "userId": "1",
          "fromNumber": "+1234567890",
          "fromName": "Gus Dakas",
          "timestamp": "2023-09-07T08:44:06.836Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "420e3dc4-f0cb-407e-ab59-478dc18434a5",
          "direction": "INBOUND",
          "text": "Thank you for providing that information. Let me check the account and see what the issue might be.",
          "toName": "Jane Doe",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Jane Doe",
          "customerPhone": "+1234567890"
        },
        {
          "userId": "1",
          "fromNumber": "",
          "fromName": "Gus Dakas",
          "timestamp": "2023-08-07T03:36:49.138Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "53f67c3a-097e-436c-9b9e-2cf4dd6b13fa",
          "direction": "INBOUND",
          "text": "I'm sorry to hear that. Can you please provide me with your account email or username so I can take a look?",
          "toName": "Jane Doe",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Jane Doe",
          "customerPhone": "+1234567890"
        },
        {
          "userId": "1",
          "fromNumber": "+1234567890",
          "fromName": "Jane Doe",
          "timestamp": "2023-09-08T07:42:18.642Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "8b370f8f-1bc7-401b-9367-884c048df6f4",
          "direction": "OUTBOUND",
          "text": "I can't seem to log in to my account. It keeps giving me an error message.",
          "toName": "Gus Dakas",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Jane Doe",
          "customerPhone": "+1234567890"
        },
        {
          "userId": "1",
          "fromNumber": "+1234567890",
          "fromName": "Jane Doe",
          "timestamp": "2002-04-09T14:07:33.973Z",
          "type": "MISSED_CALL",
          "domainId": "2",
          "id": "e39c96f4-2bf7-42ee-8888-c5a1b92d0218",
          "direction": "INBOUND",
          "text": "",
          "toName": "Gus Dakas",
          "chatGPTSummary": null,
          "toDepartment": "Sales",
          "fromDepartment": "Customer",
          "customerName": "Jane Doe",
          "customerPhone": "+1234567890"
        },
        {
          "userId": "1",
          "fromNumber": "",
          "fromName": "Gus Dakas",
          "timestamp": "2027-01-02T00:22:50.554Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "f12a4da1-6d2a-4981-911a-90d7e8194d8b",
          "direction": "INBOUND",
          "text": "Hello! I'd be happy to assist you. Could you please provide me with your username or email address associated with the account?",
          "toName": "Jane Doe",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Jane Doe",
          "customerPhone": "+1234567890"
        }
      ]
    },
    {
      "userId": "2",
      "phoneNumber": "",
      "customerName": "Jenna Harris",
      "timestamp": "2066-10-01T08:16:54.552Z",
      "type": "CHAT",
      "customerCommunicationHistory": [
        {
          "userId": "2",
          "fromNumber": "",
          "fromName": "Jenna Harris",
          "timestamp": "2066-10-01T08:16:54.552Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "06f5f45f-22e7-431b-b9f5-f6a971e78012",
          "direction": "INBOUND",
          "text": "Can you please provide me with your account email or username so I can take a look?",
          "toName": "Michael Simmons",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Michael Simmons",
          "customerPhone": "+1483274390"
        },
        {
          "userId": "2",
          "fromNumber": "+1234567890",
          "fromName": "Michael Simmons",
          "timestamp": "2040-10-17T22:30:48.907Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "72e99188-e782-4d9e-867c-cee885f6c8d1",
          "direction": "OUTBOUND",
          "text": "It keeps giving me an error message.",
          "toName": "Jenna Harris",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Michael Simmons",
          "customerPhone": "+1483274390"
        },
        {
          "userId": "2",
          "fromNumber": "+1234567890",
          "fromName": "Michael Simmons",
          "timestamp": "2098-11-17T00:57:34.734Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "7e292ec9-4795-4e0d-a817-e5adb6a73182",
          "direction": "OUTBOUND",
          "text": "Hello, how are you doing?",
          "toName": "Jenna Harris",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Michael Simmons",
          "customerPhone": "+1483274390"
        },
        {
          "userId": "2",
          "fromNumber": "",
          "fromName": "Jenna Harris",
          "timestamp": "2078-04-06T10:37:36.655Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "a62068d1-4d3c-489c-82de-29b5a448b8c7",
          "direction": "INBOUND",
          "text": "What seems to be the problem?",
          "toName": "Michael Simmons",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Michael Simmons",
          "customerPhone": "+1483274390"
        },
        {
          "userId": "2",
          "fromNumber": "+1234567890",
          "fromName": "Michael Simmons",
          "timestamp": "2064-07-22T03:25:17.141Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "ed2a27ff-9b0b-4d2a-8f53-9ea6b26b93fa",
          "direction": "OUTBOUND",
          "text": "My account email is michael@example.com",
          "toName": "Jenna Harris",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Michael Simmons",
          "customerPhone": "+1483274390"
        }
      ]
    },
    {
      "userId": "3",
      "phoneNumber": "+1234567890",
      "customerName": "Asur Joshi",
      "timestamp": "2030-07-01T18:43:10.085Z",
      "type": "CHAT",
      "customerCommunicationHistory": [
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Asur Joshi",
          "timestamp": "2030-07-01T18:43:10.085Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "098138bd-fa09-40db-a0fd-742b407b6d12",
          "direction": "INBOUND",
          "text": "Hello Tim, this is Asur Joshi. Take your time to review the pricing details. If you have any questions or need further assistance, feel free to reach out. I'm here to help!",
          "toName": "Tim Sullivan",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        },
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Tim Sullivan",
          "timestamp": "2028-05-04T02:13:46.845Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "1120a3a5-642d-491d-a5c9-73cb563228cc",
          "direction": "OUTBOUND",
          "text": "Sure, Asur. Please email me the pricing details and options at nikhil@example.com. Also, do you offer any financing options?",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        },
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Asur Joshi",
          "timestamp": "2028-02-16T14:21:24.227Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "25617f22-fd58-4ec2-9f1f-5e8b7eb83ae5",
          "direction": "INBOUND",
          "text": "Hello Tim, I'm glad to hear that you're interested in a test drive. Let me check the availability and get back to you with the available dates and times shortly.",
          "toName": "Tim Sullivan",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        },
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Tim Sullivan",
          "timestamp": "2051-09-05T07:12:27.610Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "402ac963-41e6-4e8e-89a3-ebc50142adcf",
          "direction": "OUTBOUND",
          "text": "Thank you, Asur. I have received the email. I'll review the pricing details and get back to you soon.",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        },
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Tim Sullivan",
          "timestamp": "2081-05-03T02:00:17.132Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "474d91a9-393c-4457-b5e3-1f41736a0369",
          "direction": "OUTBOUND",
          "text": "Hi Asur, I have reviewed the pricing details and options. I'm interested in scheduling a test drive. Can you provide me with the available dates and times?",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        },
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Asur Joshi",
          "timestamp": "2031-12-04T10:48:56.301Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "56c4a8dd-0f43-4bd3-b1dc-9e2645e30869",
          "direction": "INBOUND",
          "text": "Hi Tim, this is Asur Joshi from XYZ Motors. We have a range of car models available. Can you please let me know your preferences or any specific features you're looking for?",
          "toName": "Tim Sullivan",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        },
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Tim Sullivan",
          "timestamp": "2046-01-03T13:14:03.818Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "9e80b584-8909-4aca-9353-407d44cf1369",
          "direction": "OUTBOUND",
          "text": "Hi Asur, I'm interested in purchasing the XYZ car model. Can you provide me with more information on the pricing and available options?",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        },
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Asur Joshi",
          "timestamp": "2062-08-24T20:56:19.366Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "b7a1b5b4-9ec6-45aa-b39d-03b6ff18a42c",
          "direction": "INBOUND",
          "text": "Hello Tim, this is Asur Joshi from XYZ Motors. I have the pricing details and available options for the XYZ car model ready. Shall I email them to you?",
          "toName": "Tim Sullivan",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        },
        {
          "userId": "3",
          "fromNumber": "+1234567890",
          "fromName": "Tim Sullivan",
          "timestamp": "2080-02-24T04:46:43.092Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "ba71926c-2e0d-4144-9c64-2338ea0e0632",
          "direction": "OUTBOUND",
          "text": "Hello, I'm interested in purchasing a car. Can you provide me with some information on the available models?",
          "toName": "Asur Joshi",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tim Sullivan",
          "customerPhone": "+1234566874"
        }
      ]
    },
    {
      "userId": "7",
      "phoneNumber": "+1234567890",
      "customerName": "Ugo Akuwudike",
      "timestamp": "2080-02-25T10:46:01.187Z",
      "type": "CHAT",
      "customerCommunicationHistory": [
        {
          "userId": "7",
          "fromNumber": "+1234567890",
          "fromName": "Ugo Akuwudike",
          "timestamp": "2080-02-25T10:46:01.187Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "1e4d08eb-822b-4b6b-957a-4ca7631adab3",
          "direction": "OUTBOUND",
          "text": "It keeps giving me an error message.",
          "toName": "Jenna Harris",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Ugo Akuwudike",
          "customerPhone": "+1788776655"
        },
        {
          "userId": "7",
          "fromNumber": "11234565656",
          "fromName": "Jenna Harris",
          "timestamp": "2093-10-20T18:27:10.029Z",
          "type": "VM",
          "domainId": "2",
          "id": "7949cf63-848d-43c4-89b7-14067681a56a",
          "direction": "INBOUND",
          "text": "Thank you for calling us. We will be right back at you",
          "toName": "Ugo Akuwudike",
          "chatGPTSummary": null,
          "toDepartment": "Customer",
          "fromDepartment": "Marketing",
          "customerName": "Ugo Akuwudike",
          "customerPhone": "+1788776655"
        },
        {
          "userId": "7",
          "fromNumber": "+1234567890",
          "fromName": "Ugo Akuwudike",
          "timestamp": "2005-09-19T19:26:26.513Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "9fb966ed-67dc-488d-900a-9328a6ae2160",
          "direction": "OUTBOUND",
          "text": "Hello, how are you doing?",
          "toName": "Jenna Harris",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Ugo Akuwudike",
          "customerPhone": "+1788776655"
        },
        {
          "userId": "7",
          "fromNumber": "",
          "fromName": "Jenna Harris",
          "timestamp": "2028-03-04T04:22:13.350Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "b61854be-7a9e-4c2b-a640-a1333dd8e605",
          "direction": "INBOUND",
          "text": "What seems to be the problem?",
          "toName": "Ugo Akuwudike",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Ugo Akuwudike",
          "customerPhone": "+1788776655"
        }
      ]
    },
    {
      "userId": "4",
      "phoneNumber": "+1234567890",
      "customerName": "Tom Hardy",
      "timestamp": "2024-02-21T05:00:51.695Z",
      "type": "CHAT",
      "customerCommunicationHistory": [
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Tom Hardy",
          "timestamp": "2024-02-21T05:00:51.695Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "4268814d-1672-479f-8343-c42cbd7599db",
          "direction": "OUTBOUND",
          "text": "Hello, I'm interested in purchasing a car. Can you provide me with some information on the available models?",
          "toName": "Namita Kyal",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Tom Hardy",
          "timestamp": "2080-04-21T21:21:27.489Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "76b5cebd-0f3e-4266-aba0-295b3a1d2bf6",
          "direction": "OUTBOUND",
          "text": "Sure, Namita. Please email me the pricing details and options at nikhil@example.com. Also, do you offer any financing options?",
          "toName": "Namita Kyal",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Namita Kyal",
          "timestamp": "2045-01-15T04:39:49.735Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "78441e5a-7639-420f-8163-201c0dff35c1",
          "direction": "INBOUND",
          "text": "Hello Tom, this is Namita Kyal. Take your time to review the pricing details. If you have any questions or need further assistance, feel free to reach out. I'm here to help!",
          "toName": "Tom Hardy",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Namita Kyal",
          "timestamp": "2048-03-28T09:56:08.621Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "7f4113df-b65e-4260-80c1-2794cd2f44f7",
          "direction": "INBOUND",
          "text": "Hello Tom, I'm glad to hear that you're interested in a test drive. Let me check the availability and get back to you with the available dates and times shortly.",
          "toName": "Tom Hardy",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Tom Hardy",
          "timestamp": "2056-05-30T12:19:18.549Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "93763f1c-fcc1-4897-b7f9-2ab4bd64727a",
          "direction": "OUTBOUND",
          "text": "Hi Namita, I'm interested in purchasing the XYZ car model. Can you provide me with more information on the pricing and available options?",
          "toName": "Namita Kyal",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Tom Hardy",
          "timestamp": "2083-08-03T22:17:50.469Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "9e2035a8-6d0c-4a4a-9389-7435e0498abc",
          "direction": "OUTBOUND",
          "text": "Thank you, Namita. I have received the email. I'll review the pricing details and get back to you soon.",
          "toName": "Namita Kyal",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Namita Kyal",
          "timestamp": "2088-10-01T15:17:45.523Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "b20c132e-4284-4c6b-88ee-59c98cd1d6b5",
          "direction": "INBOUND",
          "text": "Hello Tom, this is Namita Kyal from XYZ Motors. I have the pricing details and available options for the XYZ car model ready. Shall I email them to you?",
          "toName": "Tom Hardy",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Tom Hardy",
          "timestamp": "2053-01-14T23:56:52.474Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "d10797c3-eb20-46a4-9328-3880e0de2cb8",
          "direction": "OUTBOUND",
          "text": "Hi Namita, I have reviewed the pricing details and options. I'm interested in scheduling a test drive. Can you provide me with the available dates and times?",
          "toName": "Namita Kyal",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "4",
          "fromNumber": "+1234567890",
          "fromName": "Namita Kyal",
          "timestamp": "2042-11-25T15:52:12.392Z",
          "type": "CHAT",
          "domainId": "2",
          "id": "e555304a-95aa-418e-84af-79d4683f8655",
          "direction": "INBOUND",
          "text": "Hi Tom, this is Asur Joshi from XYZ Motors. We have a range of car models available. Can you please let me know your preferences or any specific features you're looking for?",
          "toName": "Tom Hardy",
          "chatGPTSummary": null,
          "toDepartment": null,
          "fromDepartment": null,
          "customerName": "Tom Hardy",
          "customerPhone": "+1234565656"
        }
      ]
    },
    {
      "userId": "5",
      "phoneNumber": "11234565656",
      "customerName": "Shaurya Verma",
      "timestamp": "2023-02-21T16:03:30.498Z",
      "type": "MISSED_CALL",
      "customerCommunicationHistory": [
        {
          "userId": "5",
          "fromNumber": "11234565656",
          "fromName": "Shaurya Verma",
          "timestamp": "2023-02-21T16:03:30.498Z",
          "type": "MISSED_CALL",
          "domainId": "2",
          "id": "abd38961-f57e-41d2-9fb9-c50dbc6979a2",
          "direction": "INBOUND",
          "text": "",
          "toName": "Namita Kyal",
          "chatGPTSummary": null,
          "toDepartment": "Sales",
          "fromDepartment": "Customer",
          "customerName": "Shaurya Verma",
          "customerPhone": "+1234565656"
        },
        {
          "userId": "5",
          "fromNumber": "11234565656",
          "fromName": "Namita Kyal",
          "timestamp": "2034-08-01T12:13:40.329Z",
          "type": "VM",
          "domainId": "2",
          "id": "d89a666d-b567-4072-9371-cbe01d0e966a",
          "direction": "INBOUND",
          "text": "Thank you for calling us. We will be right back at you",
          "toName": "Shaurya Verma",
          "chatGPTSummary": null,
          "toDepartment": "Customer",
          "fromDepartment": "Sales",
          "customerName": "Shaurya Verma",
          "customerPhone": "+1234565656"
        }
      ]
    }
  ];

  export default data;